languageCode = "en"
languageName = "English"
displayName = "EN"
isoCode = "en"
weight = 1
rtl = false

title = "VINOSA TRAVEL"
logo = "img/vinosatravel_logo-500x500/vinosatravel_logo.png"
description = "Adventure | Leisure | Tour"
copyright = ":copyright: 2023 Vinosa Travel | Secured by CloudFlare | Designed by @conan97zhang"

dateFormat = "2 January 2006"

[author]
  name = "Vinosa Travel"
  image = "img/vinosatravel_logo-500x500/vinosatravel_logo.png"
  headline = "Adventure | Leisure | Tour"
  bio = "Adventure | Leisure | Tour"
  links = [
    { circle-info = "/stay-connected" },
  ]
